#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBox;
                ref class Button;
                ref class ListView;
            }
        }
    }
}

namespace App1
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Grid^ MainGrid;
        private: ::Windows::UI::Xaml::Controls::TextBox^ SearchBox;
        private: ::Windows::UI::Xaml::Controls::Button^ Search_Button;
        private: ::Windows::UI::Xaml::Controls::Button^ All_Stock_Button;
        private: ::Windows::UI::Xaml::Controls::Button^ Add_To_Portfolio_Button;
        private: ::Windows::UI::Xaml::Controls::Button^ Back_Button;
        private: ::Windows::UI::Xaml::Controls::ListView^ StockList;
    };
}

